### ISSUE TITLE
LICENSE file no longer being included in PyPI source

### ISSUE THREAD

**Issue by xylar** [microsoft/kiota-python#372]
It seems like with the release of 1.4.0, the LICENSE file is missing from the source files (at least for microsoft-kiota-abstractions) on PyPI, see:
https://files.pythonhosted.org/packages/d2/61/c31b5fb0202ad22e4dfe7329504ea2c72b947b485f7ec3957c00c16d0d9f/microsoft_kiota_abstractions-1.4.0.tar.gz
I presume they weren't dropped on purpose.

**Comment by andrueastman** [comment]
Thanks for catching this @xylar 

We'll resolve this in the next release

**Comment by xylar** [comment]
Sounds good.
